### ISSUE TITLE
Error while validating the service descriptor exception after AddLockableNavigationManager

### ISSUE THREAD

**Issue by JasonKroll** [uecasm/Mirality.Blazor.Routing#2] opened 2022-06-15 05:12 UTC
I get the following exception on the `builder.Build()` call.

`Error while validating the service descriptor 'ServiceType: Mirality.Blazor.Routing.Internals.LockableNavigationManager Lifetime: Singleton ImplementationType: Mirality.Blazor.Routing.Internals.LockableNavigationManager': Cannot consume scoped service 'Microsoft.AspNetCore.Components.NavigationManager' from singleton 'Mirality.Blazor.Routing.Internals.LockableNavigationManager'.`

I followed the basic setup from the readme in a Blazor Server app.

If I change the `AddLockableNavigationManager` extension method to use `AddScoped` it works.

`services.AddScoped<LockableNavigationManager>();`
`services.AddScoped<ICustomNavigationManager>(sp => sp.GetRequiredService<LockableNavigationManager>());`
`services.AddScoped<ILockableNavigationManager>(sp => sp.GetRequiredService<LockableNavigationManager>());`

**Comment by uecasm** [comment] 2022-06-15 06:44
This is actually a duplicate of #1, but I'll leave it open for now as this is a more concise description.

**Closed as completed** 2022-06-15 07:02 UTC
